export default {
  tabs: {
    home: 'Home',
    orders: 'Orders',
    profile: 'Profile',
    places: 'Places',
  },
  mainScreen: {
    headerText: 'Delivery to',
    onlyDelivery: 'Only Delivery',
  },
  truckScreen: {
    menuTitle: 'Menu',
    aboutUs: 'About us',
    redirectButton: 'Go to cart',
  },
  aboutTrackScreen: {
    subhead: 'What to eat here',
    address: 'Where we are',
    schedule: 'Schedule',
  },
  welcomeScreen: {
    title1: 'Meet Lunché',
    desc1: 'Finding Food Trucks has never been easier',
    title2: 'Order Street Food',
    desc2: 'It’s pretty easy in Lunché. We have more then 100 trucks food in base',
    title3: 'Pickup & Delivery',
    desc3: 'Choose options that will work for you better and we will take care about anything else',
    orderButton: "LET'S ORDER",
  },
  dishModal: {
    addToOrderButton: 'Add to order',
  },
  cartScreen: {
    headerTitle: 'Your Order',
    primaryBtn: 'Continue',
    order: 'Order',
    fee: 'Fee',
    totalDiscounts: 'Total discounts',
    total: 'Total (inc. VAT)',
    commentPlaceholder: 'Add your comment here',
  },
  checkoutScreen: {
    headerTitle: 'Checkout',
    pickUpBtn: 'Pick up',
    deliveryBtn: 'Delivery',
    pickUpLabel: 'Pick up',
    asap: 'ASAP',
    personalInfo: 'Personal information',
    note: 'This information you should use as login for further enters to the app',
    deliverAddress: 'Deliver address',
    deliveryDate: 'Deliver time',
    pickupAt: 'Pickup at',
    pickUpAddress: 'Pickup address',
    submitBtn: 'Continue',
    scheduled: 'Scheduled',
    chooseTime: 'Choose a time',
    paymentLabel: 'Payment method',
    changePaymentMethod: 'Change method',
  },
  changeAddressModal: {
    title: 'Find restaurants near you',
    description: 'Please enter your location or allow access to your location to find restaurants near you.',
    savedLocations: 'Your location',
    recentLocations: 'Recent locations',
  },
  searchTruckModal: {
    inputPlaceholder: 'Type here what you want',
    notFound: 'No found',
    placeholder: 'But don’t worry try again',
  },
  favoritePlacesScreen: {
    headerTitle: 'Saved Places',
  },
  signInScreen: {
    title: 'Welcome',
    subhead: 'Enter your Phone number for sign in',
    signInButton: 'Sign in',
    phoneNumberLabel: 'Phone Number',
  },
  verifyCodeScreen: {
    title: 'Verify phone number',
    subhead: 'Enter the 4-Digit code sent to you at',
    confirmButton: 'Verify',
    terms: 'By Signing up you agree to our Terms Conditions & Privacy Policy.',
    notReceive: "Didn't receive code?",
    resend: 'Resend Again',
  },
  ordersScreen: {
    headerTitle: 'Orders',
    reorder: 'Reorder',
    orderTracker: 'Order Tracker',
  },
  paymentScreen: {
    headerTitle: 'Order Summary',
    cash: 'Cash',
    addNewCard: 'Add a new card',
    chooseMethod: 'Choose method',
    saveMethod: 'Save',
  },
  cardModal: {
    headerTitle: 'Add a new card',
    cardDetails: 'Card details',
    note: 'This card will only be charged when you place an order.',
    saveCard: 'Save card',
  },
  successOrderScreen: {
    mainText: 'Thanks for your order',
    mainButton: 'Go to the order tracker',
  },
  orderTrackerScreen: {
    headerTitle: 'Order tracker',
    estimatedTimeCooking: 'Estimated cooking time',
    estimatedTimeDelivery: 'Estimated delivery time',
    getDirectionBtn: 'get direction',
    orderNumber: 'Order',
    paymentMethod: 'Payment method',
    order: 'Order',
  },
  accountScreen: {
    headerTitle: 'Account Settings',
    subtitle: 'Update your settings like notifications, payments, profile edit etc.',
    profileTitle: 'Profile information',
    profileSubtext: 'Change your account information',
    placesTitle: 'Saved Places',
    placesSubtext: 'Check out your saved places',
    paymentTitle: 'Payment Methods',
    paymentSubtext: 'Add your credit & debit cards',
    locationTitle: 'Locations',
    locationSubtext: 'Add or remove your delivery locations',
    sectionMore: 'More',
    rateUsTitle: 'Rate Us',
    rateUsSubtext: 'Rate us playstore, appstore',
    FAQTitle: 'FAQ',
    FAQSubtext: 'Frequently asked questions',
    LogoutTitle: 'Logout',
  },
  profileDetailsScreen: {
    headerTitle: 'Profile Details',
    saveButton: 'Change Settings',
  },
  locationsScreen: {
    headerTitle: 'Your address',
    addLocation: 'Add a new address',
    recentTitle: 'Recent',
    saveLocationTitle: 'Your locations',
  },
  creditCardsScreen: {
    headerTitle: 'Your Credit Cards',
    addCard: 'Add a new card',
  },
  totals: {
    order: 'Order',
    fee: 'Fee',
    deliveryFee: 'Delivery fee',
    totalDiscounts: 'Total discounts',
    total: 'Total (inc. VAT)',
  },
  common: {
    cancel: 'Cancel',
    select: 'Select',
    applePay: 'Apple Pay',
    contacts: 'Contacts',
  },
  errors: {
    serverError: 'Server Error',
    statusCode: 'Status code: {{code}}',
    enterCorrectCode: 'Please enter the correct code',
    stripeError: 'Stripe Error',
  },
  validation: {
    required: 'Field is required',
    minString: 'Must be at least {{value}} characters',
    invalidEmail: 'Must be a valid email',
    emailNotExists: 'User with this email not found',
    incorrectPassword: 'Wrong password',
    emailAlreadyExists: 'User with this email already exists',
    notFound: 'Not found',
  },
} as const
